require 'set'
require 'digest/sha1'
require 'pathname'
require 'tmpdir'
require 'open-uri'
require 'xot/inspectable'
require 'reflex'

require 'processing/extension'
require 'processing/app'
require 'processing/window'

require 'processing/vector'
require 'processing/image'
require 'processing/font'
require 'processing/touch'
require 'processing/shape'
require 'processing/shader'
require 'processing/capture'
require 'processing/graphics_context'
require 'processing/graphics'
require 'processing/context'
