require 'set'
require 'strscan'
require 'digest/sha1'
require 'pathname'
require 'tmpdir'
require 'uri'
require 'rexml'
require 'net/http'
require 'xot/inspectable'
require 'reflex'

require 'processing/extension'
require 'processing/app'
require 'processing/window'

require 'processing/vector'
require 'processing/image'
require 'processing/font'
require 'processing/touch'
require 'processing/shape'
require 'processing/svg'
require 'processing/shader'
require 'processing/capture'
require 'processing/graphics_context'
require 'processing/graphics'
require 'processing/events'
require 'processing/context'
