name: Release Gem

on:
  push:
    tags: ['v[0-9]*']

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: version
        id: version
        run: |
          echo value=$(ruby -e 'print "${{ github.ref }}"[/\/v([\w\.\-]+)/, 1]') >> $GITHUB_OUTPUT

      - name: create gem
        run: rake clean gem

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: upload to releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./processing-${{ steps.version.outputs.value }}.gem
          asset_name:   processing-${{ steps.version.outputs.value }}.gem
          asset_content_type: application/zip

      - name: upload to rubygems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          rake upload
